sudo: false
language: node_js

node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
  - '0.8'

before_install:
- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
- npm install -g npm@2.12

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
#  - cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
